inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 3.1.6
  Exclude:
    - 'bin/bundle'
    - 'vendor/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'db/schema.rb'
    - Schemafile
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'app/views/**/*'
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'lib/tasks/**/*'

Metrics/MethodLength:
  Max: 15

Rails:
  Enabled: true
