version: '3'

services:
  db:
    image: mysql:8.0.34
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3321:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lifeplan-network

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp/
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - lifeplan-network

volumes:
  mysql_data:

networks:
  lifeplan-network:
    external: true
