name: Rails CI
on: pull_request

jobs:
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker
        run: docker compose build web

      - name: Run Lint
        run: docker compose run web bundle exec rubocop

  Rspec:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker
        run: docker compose build

      - name: Up Docker
        run: docker compose -f docker-compose.yml -f .github/docker-compose.github.yml up -d

      - name: Setup Database
        run: docker compose exec web rails db:create db:schema:load RAILS_ENV=test

      - name: Run RSpec
        run: docker compose exec web bundle exec rspec
