name: Rails CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup network
        run: docker network create lifeplan-network

      - name: Build Docker
        run: docker compose build web

      - name: Run Lint
        run: docker compose run web bundle exec rubocop

  Rspec:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup network
        run: docker network create lifeplan-network

      - name: Build Docker
        run: docker compose build

      - name: Up Docker
        run: docker compose -f docker-compose.yml -f .github/docker-compose.github.yml up -d

      - name: Setup Database
        run: docker compose exec web rails db:create db:schema:load RAILS_ENV=test

      - name: Run RSpec
        run: docker compose exec web bundle exec rspec

  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    needs: ['Lint', 'Rspec']
    if: github.ref_name == 'main'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCLOUD_AUTH }}"

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Configure docker for artifact registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build
        env:
          IMAGE_TAG: ${{ github.run_id }}
        run: docker build -t us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/lifeplan-kanrikun-backend/${{ env.IMAGE_TAG }} .

      - name: Push
        env:
          IMAGE_TAG: ${{ github.run_id }}
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/lifeplan-kanrikun-backend/${{ env.IMAGE_TAG }}
