name: Rails CI
on: pull_request

jobs:
  Rubocop:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker compose build web

      - name: Run Rubocop
        run: docker compose run web bundle exec rubocop

  Rspec:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker compose build web

      - name: database compose up
        run: docker compose up -d

      - name: Sleep for waiting launch db
        run: sleep 10s

      - name: Setup Database
        run: docker compose run web rails db:create db:schema:load RAILS_ENV=test

      - name: Run RSpec
        run: docker compose run web bundle exec rspec
